name: lighting-gw
version: "0.1.0"
summary: Connect local lighing devices to cloud
description: A smartlighting gateway connected to AWS IoT
confinement: strict 

apps:
    lighting-gw:
        command: bin/lighting-gw
        plugs: [serial-port]

parts:
    lighting-gw:
        plugin: nodejs
        source: .
        node-engine: 6.5.0
