name: lighting-gw
version: "0.1.0"
summary: Connect local lighing devices to cloud
description: A smartlighting gateway connected to AWS IoT
confinement: devmode

apps:
    lighting-gw:
        command: bin/lighting-gw

parts:
    lighting-gw:
        plugin: nodejs
        node-packages:
            - lighting-gw
        node-engine: 6.5.0
