name: lighting-gw
version: "0.1.1"
summary: Connect local lighing devices to cloud
description: This is a smart lighting gateway, which communicates with Zigbee Home Automation network and connect it to cloud.
# confinement: strict 
confinement: devmode

apps:
    lighting-gw:
        daemon: simple
        command: bin/lighting-gw
        plugs: [serial-port, network, network-bind, home]

parts:
    lighting-gw:
        plugin: nodejs
        source: .
        node-engine: 6.10.1
